package com.hhy.beans;

public class DictionaryType {

    private String id;

    private String name;

    private String description;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_type.name
     *
     * @return the value of tbl_dictionary_type.name
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_type.name
     *
     * @param name the value for tbl_dictionary_type.name
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_type.description
     *
     * @return the value of tbl_dictionary_type.description
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_type.description
     *
     * @param description the value for tbl_dictionary_type.description
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        return "DictionaryType{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}