package com.hhy.beans;

public class DictionaryValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.id
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.text
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.order_no
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    private Long orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dictionary_value.typeid
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    private String typeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.id
     *
     * @return the value of tbl_dictionary_value.id
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.id
     *
     * @param id the value for tbl_dictionary_value.id
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.value
     *
     * @return the value of tbl_dictionary_value.value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.value
     *
     * @param value the value for tbl_dictionary_value.value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.text
     *
     * @return the value of tbl_dictionary_value.text
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.text
     *
     * @param text the value for tbl_dictionary_value.text
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.order_no
     *
     * @return the value of tbl_dictionary_value.order_no
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.order_no
     *
     * @param orderNo the value for tbl_dictionary_value.order_no
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_dictionary_value.typeid
     *
     * @return the value of tbl_dictionary_value.typeid
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public String getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_dictionary_value.typeid
     *
     * @param typeid the value for tbl_dictionary_value.typeid
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    public void setTypeid(String typeid) {
        this.typeid = typeid == null ? null : typeid.trim();
    }

    @Override
    public String toString() {
        return "DictionaryValue{" +
                "id='" + id + '\'' +
                ", value='" + value + '\'' +
                ", text='" + text + '\'' +
                ", orderNo=" + orderNo +
                ", typeid='" + typeid + '\'' +
                '}';
    }
}