package com.hhy.mapper;

import com.hhy.beans.DictionaryType;
import com.hhy.beans.DictionaryTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int countByExample(DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int deleteByExample(DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int insert(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int insertSelective(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    List<DictionaryType> selectByExample(DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    DictionaryType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int updateByExampleSelective(@Param("record") DictionaryType record, @Param("example") DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int updateByExample(@Param("record") DictionaryType record, @Param("example") DictionaryTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int updateByPrimaryKeySelective(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_type
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int updateByPrimaryKey(DictionaryType record);
}