package com.hhy.mapper;

import com.hhy.beans.DictionaryValue;
import com.hhy.beans.DictionaryValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictionaryValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int countByExample(DictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int deleteByExample(DictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int insert(DictionaryValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int insertSelective(DictionaryValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    List<DictionaryValue> selectByExample(DictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    DictionaryValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int updateByExampleSelective(@Param("record") DictionaryValue record, @Param("example") DictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int updateByExample(@Param("record") DictionaryValue record, @Param("example") DictionaryValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int updateByPrimaryKeySelective(DictionaryValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dictionary_value
     *
     * @mbggenerated Wed Mar 01 09:19:13 CST 2023
     */
    int updateByPrimaryKey(DictionaryValue record);
}